name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mark workspace as safe for Git
        run: git config --global --add safe.directory /github/workspace
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@v2.1.0
        with:
          slug: easy-hierarchy
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
